# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "create xcframework for ReactiveObjC"
  lane :make_xcframework do
    # add actions here: https://docs.fastlane.tools/actions
#    create_xcframework(
#        workspace: 'ReactiveObjC.xcworkspace',
#        scheme: 'ReactiveObjC-iOS',
#        product_name: 'ReactiveObjC', # optional if scheme doesnt match the name of your framework
#        destinations: ['iOS'],
#        xcframework_output_directory: 'xcframeworks'
#    )
  end
end
